# Generated by Django 5.2.8 on 2025-12-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='default_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Standard daily charge for this student', max_digits=6),
        ),
    ]
