# Generated by Django 5.2.8 on 2025-12-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0002_child_default_daily_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('period_start', models.DateField(help_text='Billing period start')),
                ('period_end', models.DateField(help_text='Billing period end')),
                ('total_days_present', models.IntegerField(default=0)),
                ('daily_rate_applied', models.DecimalField(decimal_places=2, max_digits=6)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Days * Rate', max_digits=10)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Positive for extra charge, Negative for discount', max_digits=10)),
                ('adjustment_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='children.child')),
            ],
        ),
    ]
