# Generated by Django 5.2.8 on 2026-01-01 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0002_child_default_daily_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('MEAL', 'Meal / Snack'), ('NAP', 'Nap Time'), ('DIAPER', 'Diaper / Potty'), ('LEARNING', 'Learning / Activity'), ('PLAY', 'Play Time'), ('NOTE', 'General Note')], max_length=20)),
                ('title', models.CharField(help_text='e.g. Lunch, Afternoon Nap', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Details like 'Ate all food' or 'Slept 1 hour'", null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='children.child')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
