# Generated by Django 5.2.8 on 2026-01-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('INFANT', 'Small (Infants)'), ('TODDLER', 'Medium (Toddlers)'), ('PRESCHOOL', 'Large (Preschoolers)')], default='PRESCHOOL', max_length=20)),
                ('start_time', models.TimeField()),
                ('title', models.CharField(help_text='e.g. Learning Session', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. (Maths/ABC)', max_length=200)),
                ('color_theme', models.CharField(choices=[('secondary', 'Grey (Standard)'), ('success', 'Green (Learning)'), ('info', 'Blue (Reading/Puzzle)'), ('primary', 'Dark Blue (Lunch)'), ('warning', 'Yellow (Departure)')], default='secondary', max_length=20)),
                ('icon', models.CharField(default='bi-circle', help_text='Bootstrap Icon class, e.g. bi-book', max_length=50)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
