# Generated by Django 5.2.8 on 2025-12-05 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_spouse_name', models.CharField(max_length=100, verbose_name='Father/Spouse Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('Teacher', 'Teacher'), ('Assistant', 'Assistant'), ('Admin', 'Administrator'), ('Cleaner', 'Cleaning Staff'), ('Driver', 'Driver'), ('Security', 'Security')], default='Teacher', max_length=50)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('salary', models.DecimalField(decimal_places=2, help_text='Monthly Salary', max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Resigned', 'Resigned')], default='Active', max_length=20)),
            ],
        ),
    ]
